// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct or session-pooler connection; the app's
    // DATABASE_URL may point at the transaction pooler (port 6543).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
